### ISSUE TITLE
Update cava version

### ISSUE THREAD

**Issue by kc-kc** [azahi/ricerlay#2]
I am a new Gentoo user, and tried to use this project to install [cava](https://github.com/karlstav/cava), however the version is slightly out of date and doesn't work well. I would love to contribute, however, I have literally installed Gentoo earlier today and have no idea how to put together an `.ebuild`. I hope updating the version of cava to `0.7.2` wouldn't be too difficult.

As a little pointer for anyone who wants to do this (and myself when once I figure out ebuilds), [thegreatmcpain](https://gpo.zugaina.org/Overlays/thegreatmcpain) overlay can install the bleeding-edge release and works great.

**Comment by azahi** [comment]
I've managed to update the ebuild and also added a live version as well. 

I'm not sure that it will work with `USE=pulseaudio` or `USE=portaudio` because I don't use either of these.

**Comment by kc-kc** [comment]
I've enabled `USE=pulseaudio`, and the live build seems to work perfectly. I don't happen to use portaudio though, but thank you regardless for the help!
